language: node_js
node_js:
  - '10'
env:
  global:
    - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
before_script:
  - npm install
  - npm install -g jest-cli
script:
  - CI=false npm run build
  - npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email: false
